import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'te' | 'ta' | 'ml' | 'mr' | 'or' | 'gu' | 'pa' | 'bh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.yourIdea': 'Your Idea',
    'nav.businessPlan': 'Business Plan',
    'nav.designStudio': 'Design Studio',
    'nav.marketing': 'Marketing',
    'nav.suppliers': 'Suppliers',
    'nav.logout': 'Log Out',
    
    // Dashboard
    'dashboard.hero.title': 'Start any small business today.',
    'dashboard.hero.description': 'Transform your business idea into a launch-ready business kit with AI-powered tools designed for Indian entrepreneurs.',
    'dashboard.hero.cta': 'Get Started',
    'dashboard.stats.ideasAnalyzed': 'Ideas Analyzed',
    'dashboard.stats.plansGenerated': 'Plans Generated',
    'dashboard.stats.designsCreated': 'Designs Created',
    'dashboard.stats.marketingAssets': 'Marketing Assets',
    'dashboard.features.shareIdea': 'Share Your Idea',
    'dashboard.features.shareIdea.desc': 'Tell us your business idea in any language using voice or text',
    'dashboard.features.aiPlan': 'AI Business Plan',
    'dashboard.features.aiPlan.desc': 'Get a comprehensive business plan generated by AI',
    'dashboard.features.designStudio': 'Design Studio',
    'dashboard.features.designStudio.desc': 'Create logos, mockups, and visual content for your brand',
    'dashboard.features.marketing': 'Marketing Hub',
    'dashboard.features.marketing.desc': 'Generate marketing content and promotional materials',
    'dashboard.progress': 'Progress',
    'dashboard.nextSteps': 'Suggested Next Steps',
    'dashboard.nextSteps.desc': "Here's what we recommend to get your business started",
    'dashboard.step1': 'Share your business idea',
    'dashboard.step1.desc': 'Use voice or text to tell us about your business concept',
    'dashboard.step2': 'Generate your business plan',
    'dashboard.step2.desc': 'AI will create a comprehensive business plan for you',
    'dashboard.step3': 'Create your brand identity',
    'dashboard.step3.desc': 'Design logos, business cards, and marketing materials',
    'dashboard.startNow': 'Start Now',
    'dashboard.comingNext': 'Coming Next',
    
    // Suppliers
    'suppliers.title': 'Suppliers & Local Dealers',
    'suppliers.description': 'Browse our directory or discover dealers near you',
    'suppliers.directory': 'Suppliers Directory',
    'suppliers.localDealers': 'Local Dealers',
    'suppliers.search': 'Search suppliers or materials...',
    'suppliers.category': 'Category',
    'suppliers.city': 'City',
    'suppliers.allCategories': 'All Categories',
    'suppliers.allCities': 'All Cities',
    'suppliers.listView': 'List View',
    'suppliers.mapView': 'Map View',
    'suppliers.noResults': 'No Suppliers Found',
    'suppliers.noResults.desc': 'Try adjusting your search criteria or browse all suppliers',
    'suppliers.contact': 'Contact Supplier',
    'suppliers.directions': 'Get Directions',
    'suppliers.totalSuppliers': 'Total Suppliers',
    'suppliers.citiesCovered': 'Cities Covered',
    'suppliers.categories': 'Categories',
    'suppliers.avgRating': 'Avg Rating',
  },
  hi: {
    // Navigation
    'nav.dashboard': 'डैशबोर्ड',
    'nav.yourIdea': 'आपका विचार',
    'nav.businessPlan': 'व्यवसाय योजना',
    'nav.designStudio': 'डिज़ाइन स्टूडियो',
    'nav.marketing': 'मार्केटिंग',
    'nav.suppliers': 'आपूर्तिकर्ता',
    'nav.logout': 'लॉग आउट',
    
    // Dashboard
    'dashboard.hero.title': 'आज ही कोई भी छोटा व्यवसाय शुरू करें।',
    'dashboard.hero.description': 'भारतीय उद्यमियों के लिए डिज़ाइन किए गए AI-संचालित उपकरणों के साथ अपने व्यवसाय विचार को लॉन्च-रेडी बिज़नेस किट में बदलें।',
    'dashboard.hero.cta': 'शुरू करें',
    'dashboard.stats.ideasAnalyzed': 'विचारों का विश्लेषण',
    'dashboard.stats.plansGenerated': 'योजनाएं बनाई गईं',
    'dashboard.stats.designsCreated': 'डिज़ाइन बनाए गए',
    'dashboard.stats.marketingAssets': 'मार्केटिंग संपत्ति',
    'dashboard.features.shareIdea': 'अपना विचार साझा करें',
    'dashboard.features.shareIdea.desc': 'वॉइस या टेक्स्ट का उपयोग करके किसी भी भाषा में हमें अपने व्यवसाय विचार के बारे में बताएं',
    'dashboard.features.aiPlan': 'AI व्यवसाय योजना',
    'dashboard.features.aiPlan.desc': 'AI द्वारा एक व्यापक व्यवसाय योजना प्राप्त करें',
    'dashboard.features.designStudio': 'डिज़ाइन स्टूडियो',
    'dashboard.features.designStudio.desc': 'अपने ब्रांड के लिए लोगो, मॉकअप और दृश्य सामग्री बनाएं',
    'dashboard.features.marketing': 'मार्केटिंग हब',
    'dashboard.features.marketing.desc': 'मार्केटिंग सामग्री और प्रचार सामग्री उत्पन्न करें',
    'dashboard.progress': 'प्रगति',
    'dashboard.nextSteps': 'सुझाए गए अगले कदम',
    'dashboard.nextSteps.desc': 'अपना व्यवसाय शुरू करने के लिए हम यही अनुशंसा करते हैं',
    'dashboard.step1': 'अपना व्यवसाय विचार साझा करें',
    'dashboard.step1.desc': 'अपनी व्यवसाय अवधारणा के बारे में बताने के लिए वॉइस या टेक्स्ट का उपयोग करें',
    'dashboard.step2': 'अपनी व्यवसाय योजना बनाएं',
    'dashboard.step2.desc': 'AI आपके लिए एक व्यापक व्यवसाय योजना तैयार करेगा',
    'dashboard.step3': 'अपनी ब्रांड पहचान बनाएं',
    'dashboard.step3.desc': 'लोगो, बिजनेस कार्ड और मार्केटिंग सामग्री डिज़ाइन करें',
    'dashboard.startNow': 'अभी शुरू करें',
    'dashboard.comingNext': 'आगे आ रहा है',
    
    // Suppliers
    'suppliers.title': 'आपूर्तिकर्ता और स्थानीय डीलर',
    'suppliers.description': 'हमारी निर्देशिका ब्राउज़ करें या अपने आस-पास डीलरों को खोजें',
    'suppliers.directory': 'आपूर्तिकर्ता निर्देशिका',
    'suppliers.localDealers': 'स्थानीय डीलर',
    'suppliers.search': 'आपूर्तिकर्ता या सामग्री खोजें...',
    'suppliers.category': 'श्रेणी',
    'suppliers.city': 'शहर',
    'suppliers.allCategories': 'सभी श्रेणियां',
    'suppliers.allCities': 'सभी शहर',
    'suppliers.listView': 'सूची दृश्य',
    'suppliers.mapView': 'मानचित्र दृश्य',
    'suppliers.noResults': 'कोई आपूर्तिकर्ता नहीं मिला',
    'suppliers.noResults.desc': 'अपने खोज मानदंड समायोजित करें या सभी आपूर्तिकर्ताओं को ब्राउज़ करें',
    'suppliers.contact': 'आपूर्तिकर्ता से संपर्क करें',
    'suppliers.directions': 'दिशा-निर्देश प्राप्त करें',
    'suppliers.totalSuppliers': 'कुल आपूर्तिकर्ता',
    'suppliers.citiesCovered': 'शहर कवर किए गए',
    'suppliers.categories': 'श्रेणियां',
    'suppliers.avgRating': 'औसत रेटिंग',
  },
  te: {
    // Navigation
    'nav.dashboard': 'డాష్‌బోర్డ్',
    'nav.yourIdea': 'మీ ఆలోచన',
    'nav.businessPlan': 'వ్యాపార ప్రణాళిక',
    'nav.designStudio': 'డిజైన్ స్టూడియో',
    'nav.marketing': 'మార్కెటింగ్',
    'nav.suppliers': 'సరఫరాదారులు',
    'nav.logout': 'లాగ్ అవుట్',
    
    // Dashboard
    'dashboard.hero.title': 'ఈరోజే ఏదైనా చిన్న వ్యాపారాన్ని ప్రారంభించండి.',
    'dashboard.hero.description': 'భారతీయ వ్యాపారవేత్తల కోసం రూపొందించిన AI-శక్తితో కూడిన సాధనాలతో మీ వ్యాపార ఆలోచనను లాంచ్-రెడీ బిజినెస్ కిట్‌గా మార్చండి.',
    'dashboard.hero.cta': 'ప్రారంభించండి',
    'dashboard.stats.ideasAnalyzed': 'విశ్లేషించిన ఆలోచనలు',
    'dashboard.stats.plansGenerated': 'రూపొందించిన ప్రణాళికలు',
    'dashboard.stats.designsCreated': 'సృష్టించిన డిజైన్‌లు',
    'dashboard.stats.marketingAssets': 'మార్కెటింగ్ ఆస్తులు',
    'dashboard.features.shareIdea': 'మీ ఆలోచనను పంచుకోండి',
    'dashboard.features.shareIdea.desc': 'వాయిస్ లేదా టెక్స్ట్ ఉపయోగించి ఏ భాషలోనైనా మీ వ్యాపార ఆలోచన గురించి మాకు చెప్పండి',
    'dashboard.features.aiPlan': 'AI వ్యాపార ప్రణాళిక',
    'dashboard.features.aiPlan.desc': 'AI ద్వారా సమగ్ర వ్యాపార ప్రణాళికను పొందండి',
    'dashboard.features.designStudio': 'డిజైన్ స్టూడియో',
    'dashboard.features.designStudio.desc': 'మీ బ్రాండ్ కోసం లోగోలు, మాకప్‌లు మరియు విజువల్ కంటెంట్‌ను సృష్టించండి',
    'dashboard.features.marketing': 'మార్కెటింగ్ హబ్',
    'dashboard.features.marketing.desc': 'మార్కెటింగ్ కంటెంట్ మరియు ప్రచార సామగ్రిని రూపొందించండి',
    'dashboard.progress': 'పురోగతి',
    'dashboard.nextSteps': 'సూచించిన తదుపరి దశలు',
    'dashboard.nextSteps.desc': 'మీ వ్యాపారాన్ని ప్రారంభించడానికి మేము ఇది సిఫార్సు చేస్తాము',
    'dashboard.step1': 'మీ వ్యాపార ఆలోచనను పంచుకోండి',
    'dashboard.step1.desc': 'మీ వ్యాపార భావన గురించి చెప్పడానికి వాయిస్ లేదా టెక్స్ట్ ఉపయోగించండి',
    'dashboard.step2': 'మీ వ్యాపార ప్రణాళికను రూపొందించండి',
    'dashboard.step2.desc': 'AI మీ కోసం సమగ్ర వ్యాపార ప్రణాళికను సృష్టిస్తుంది',
    'dashboard.step3': 'మీ బ్రాండ్ గుర్తింపును సృష్టించండి',
    'dashboard.step3.desc': 'లోగోలు, వ్యాపార కార్డులు మరియు మార్కెటింగ్ మెటీరియల్స్‌ను డిజైన్ చేయండి',
    'dashboard.startNow': 'ఇప్పుడే ప్రారంభించండి',
    'dashboard.comingNext': 'తదుపరి వస్తోంది',
    
    // Suppliers
    'suppliers.title': 'సరఫరాదారులు & స్థానిక డీలర్లు',
    'suppliers.description': 'మా డైరెక్టరీని బ్రౌజ్ చేయండి లేదా మీ దగ్గర డీలర్లను కనుగొనండి',
    'suppliers.directory': 'సరఫరాదారుల డైరెక్టరీ',
    'suppliers.localDealers': 'స్థానిక డీలర్లు',
    'suppliers.search': 'సరఫరాదారులు లేదా మెటీరియల్స్ వెతకండి...',
    'suppliers.category': 'వర్గం',
    'suppliers.city': 'నగరం',
    'suppliers.allCategories': 'అన్ని వర్గాలు',
    'suppliers.allCities': 'అన్ని నగరాలు',
    'suppliers.listView': 'జాబితా వీక్షణ',
    'suppliers.mapView': 'మ్యాప్ వీక్షణ',
    'suppliers.noResults': 'సరఫరాదారులు కనుగొనబడలేదు',
    'suppliers.noResults.desc': 'మీ శోధన ప్రమాణాలను సర్దుబాటు చేయండి లేదా అన్ని సరఫరాదారులను బ్రౌజ్ చేయండి',
    'suppliers.contact': 'సరఫరాదారుని సంప్రదించండి',
    'suppliers.directions': 'దిశలను పొందండి',
    'suppliers.totalSuppliers': 'మొత్తం సరఫరాదారులు',
    'suppliers.citiesCovered': 'కవర్ చేసిన నగరాలు',
    'suppliers.categories': 'వర్గాలు',
    'suppliers.avgRating': 'సగటు రేటింగ్',
  },
  ta: {
    // Navigation
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.yourIdea': 'உங்கள் யோசனை',
    'nav.businessPlan': 'வணிகத் திட்டம்',
    'nav.designStudio': 'வடிவமைப்பு ஸ்டுடியோ',
    'nav.marketing': 'மார்க்கெட்டிங்',
    'nav.suppliers': 'சப்ளையர்கள்',
    'nav.logout': 'வெளியேறு',
    
    // Dashboard
    'dashboard.hero.title': 'இன்றே எந்த சிறு வணிகத்தையும் தொடங்குங்கள்.',
    'dashboard.hero.description': 'இந்திய தொழில்முனைவோருக்காக வடிவமைக்கப்பட்ட AI-இயங்கும் கருவிகளுடன் உங்கள் வணிக யோசனையை துவக்க-தயார் வணிக கிட்டாக மாற்றுங்கள்.',
    'dashboard.hero.cta': 'தொடங்குங்கள்',
    'dashboard.stats.ideasAnalyzed': 'பகுப்பாய்வு செய்யப்பட்ட யோசனைகள்',
    'dashboard.stats.plansGenerated': 'உருவாக்கப்பட்ட திட்டங்கள்',
    'dashboard.stats.designsCreated': 'உருவாக்கப்பட்ட வடிவமைப்புகள்',
    'dashboard.stats.marketingAssets': 'மார்க்கெட்டிங் சொத்துக்கள்',
    'dashboard.features.shareIdea': 'உங்கள் யோசனையைப் பகிரவும்',
    'dashboard.features.shareIdea.desc': 'குரல் அல்லது உரையைப் பயன்படுத்தி எந்த மொழியிலும் உங்கள் வணிக யோசனை பற்றி எங்களிடம் கூறுங்கள்',
    'dashboard.features.aiPlan': 'AI வணிகத் திட்டம்',
    'dashboard.features.aiPlan.desc': 'AI மூலம் விரிவான வணிகத் திட்டத்தைப் பெறுங்கள்',
    'dashboard.features.designStudio': 'வடிவமைப்பு ஸ்டுடியோ',
    'dashboard.features.designStudio.desc': 'உங்கள் பிராண்டுக்கான லோகோக்கள், மாக்அப்கள் மற்றும் காட்சி உள்ளடக்கத்தை உருவாக்குங்கள்',
    'dashboard.features.marketing': 'மார்க்கெட்டிங் மையம்',
    'dashboard.features.marketing.desc': 'மார்க்கெட்டிங் உள்ளடக்கம் மற்றும் விளம்பரப் பொருட்களை உருவாக்குங்கள்',
    'dashboard.progress': 'முன்னேற்றம்',
    'dashboard.nextSteps': 'பரிந்துரைக்கப்பட்ட அடுத்த படிகள்',
    'dashboard.nextSteps.desc': 'உங்கள் வணிகத்தைத் தொடங்க நாங்கள் பரிந்துரைப்பது இதுதான்',
    'dashboard.step1': 'உங்கள் வணிக யோசனையைப் பகிரவும்',
    'dashboard.step1.desc': 'உங்கள் வணிகக் கருத்தைப் பற்றி சொல்ல குரல் அல்லது உரையைப் பயன்படுத்தவும்',
    'dashboard.step2': 'உங்கள் வணிகத் திட்டத்தை உருவாக்குங்கள்',
    'dashboard.step2.desc': 'AI உங்களுக்காக விரிவான வணிகத் திட்டத்தை உருவாக்கும்',
    'dashboard.step3': 'உங்கள் பிராண்ட் அடையாளத்தை உருவாக்குங்கள்',
    'dashboard.step3.desc': 'லோகோக்கள், வணிக அட்டைகள் மற்றும் மார்க்கெட்டிங் பொருட்களை வடிவமைக்கவும்',
    'dashboard.startNow': 'இப்போதே தொடங்குங்கள்',
    'dashboard.comingNext': 'அடுத்து வருகிறது',
    
    // Suppliers
    'suppliers.title': 'சப்ளையர்கள் & உள்ளூர் டீலர்கள்',
    'suppliers.description': 'எங்கள் அடைவைப் பார்க்கவும் அல்லது உங்களுக்கு அருகில் உள்ள டீலர்களைக் கண்டறியவும்',
    'suppliers.directory': 'சப்ளையர்கள் அடைவு',
    'suppliers.localDealers': 'உள்ளூர் டீலர்கள்',
    'suppliers.search': 'சப்ளையர்கள் அல்லது பொருட்களைத் தேடுங்கள்...',
    'suppliers.category': 'வகை',
    'suppliers.city': 'நகரம்',
    'suppliers.allCategories': 'அனைத்து வகைகளும்',
    'suppliers.allCities': 'அனைத்து நகரங்களும்',
    'suppliers.listView': 'பட்டியல் காட்சி',
    'suppliers.mapView': 'வரைபட காட்சி',
    'suppliers.noResults': 'சப்ளையர்கள் கிடைக்கவில்லை',
    'suppliers.noResults.desc': 'உங்கள் தேடல் அளவுகோல்களைச் சரிசெய்யவும் அல்லது அனைத்து சப்ளையர்களையும் உலாவவும்',
    'suppliers.contact': 'சப்ளையரைத் தொடர்பு கொள்ளவும்',
    'suppliers.directions': 'வழிகளைப் பெறுங்கள்',
    'suppliers.totalSuppliers': 'மொத்த சப்ளையர்கள்',
    'suppliers.citiesCovered': 'உள்ளடக்கப்பட்ட நகரங்கள்',
    'suppliers.categories': 'வகைகள்',
    'suppliers.avgRating': 'சராசரி மதிப்பீடு',
  },
  ml: {
    // Navigation
    'nav.dashboard': 'ഡാഷ്ബോർഡ്',
    'nav.yourIdea': 'നിങ്ങളുടെ ആശയം',
    'nav.businessPlan': 'ബിസിനസ് പ്ലാൻ',
    'nav.designStudio': 'ഡിസൈൻ സ്റ്റുഡിയോ',
    'nav.marketing': 'മാർക്കറ്റിംഗ്',
    'nav.suppliers': 'വിതരണക്കാർ',
    'nav.logout': 'ലോഗ് ഔട്ട്',
    
    // Dashboard
    'dashboard.hero.title': 'ഇന്ന് ഏതെങ്കിലും ചെറുകിട ബിസിനസ്സ് ആരംഭിക്കുക.',
    'dashboard.hero.description': 'ഇന്ത്യൻ സംരംഭകർക്കായി രൂപകൽപ്പന ചെയ്ത AI-പവർഡ് ടൂളുകൾ ഉപയോഗിച്ച് നിങ്ങളുടെ ബിസിനസ് ആശയത്തെ ലോഞ്ച്-റെഡി ബിസിനസ് കിറ്റാക്കി മാറ്റുക.',
    'dashboard.hero.cta': 'ആരംഭിക്കുക',
    'dashboard.stats.ideasAnalyzed': 'വിശകലനം ചെയ്ത ആശയങ്ങൾ',
    'dashboard.stats.plansGenerated': 'സൃഷ്ടിച്ച പ്ലാനുകൾ',
    'dashboard.stats.designsCreated': 'സൃഷ്ടിച്ച ഡിസൈനുകൾ',
    'dashboard.stats.marketingAssets': 'മാർക്കറ്റിംഗ് അസറ്റുകൾ',
    'dashboard.features.shareIdea': 'നിങ്ങളുടെ ആശയം പങ്കിടുക',
    'dashboard.features.shareIdea.desc': 'വോയ്‌സ് അല്ലെങ്കിൽ ടെക്‌സ്റ്റ് ഉപയോഗിച്ച് ഏതെങ്കിലും ഭാഷയിൽ നിങ്ങളുടെ ബിസിനസ്സ് ആശയം ഞങ്ങളോട് പറയുക',
    'dashboard.features.aiPlan': 'AI ബിസിനസ് പ്ലാൻ',
    'dashboard.features.aiPlan.desc': 'AI വഴി സമഗ്രമായ ബിസിനസ് പ്ലാൻ നേടുക',
    'dashboard.features.designStudio': 'ഡിസൈൻ സ്റ്റുഡിയോ',
    'dashboard.features.designStudio.desc': 'നിങ്ങളുടെ ബ്രാൻഡിനായി ലോഗോകൾ, മോക്കപ്പുകൾ, വിഷ്വൽ ഉള്ളടക്കം എന്നിവ സൃഷ്ടിക്കുക',
    'dashboard.features.marketing': 'മാർക്കറ്റിംഗ് ഹബ്',
    'dashboard.features.marketing.desc': 'മാർക്കറ്റിംഗ് ഉള്ളടക്കവും പ്രമോഷണൽ മെറ്റീരിയലുകളും സൃഷ്ടിക്കുക',
    'dashboard.progress': 'പുരോഗതി',
    'dashboard.nextSteps': 'നിർദ്ദേശിച്ച അടുത്ത ഘട്ടങ്ങൾ',
    'dashboard.nextSteps.desc': 'നിങ്ങളുടെ ബിസിനസ്സ് ആരംഭിക്കാൻ ഞങ്ങൾ ഇത് ശുപാർശ ചെയ്യുന്നു',
    'dashboard.step1': 'നിങ്ങളുടെ ബിസിനസ്സ് ആശയം പങ്കിടുക',
    'dashboard.step1.desc': 'നിങ്ങളുടെ ബിസിനസ് ആശയം പറയാൻ വോയ്‌സ് അല്ലെങ്കിൽ ടെക്‌സ്റ്റ് ഉപയോഗിക്കുക',
    'dashboard.step2': 'നിങ്ങളുടെ ബിസിനസ് പ്ലാൻ സൃഷ്ടിക്കുക',
    'dashboard.step2.desc': 'AI നിങ്ങൾക്കായി സമഗ്രമായ ബിസിനസ് പ്ലാൻ സൃഷ്ടിക്കും',
    'dashboard.step3': 'നിങ്ങളുടെ ബ്രാൻഡ് ഐഡന്റിറ്റി സൃഷ്ടിക്കുക',
    'dashboard.step3.desc': 'ലോഗോകൾ, ബിസിനസ് കാർഡുകൾ, മാർക്കറ്റിംഗ് മെറ്റീരിയലുകൾ എന്നിവ ഡിസൈൻ ചെയ്യുക',
    'dashboard.startNow': 'ഇപ്പോൾ ആരംഭിക്കുക',
    'dashboard.comingNext': 'അടുത്തത് വരുന്നു',
    
    // Suppliers
    'suppliers.title': 'വിതരണക്കാരും പ്രാദേശിക ഡീലർമാരും',
    'suppliers.description': 'ഞങ്ങളുടെ ഡയറക്ടറി ബ്രൗസ് ചെയ്യുക അല്ലെങ്കിൽ നിങ്ങളുടെ അടുത്തുള്ള ഡീലർമാരെ കണ്ടെത്തുക',
    'suppliers.directory': 'വിതരണക്കാരുടെ ഡയറക്ടറി',
    'suppliers.localDealers': 'പ്രാദേശിക ഡീലർമാർ',
    'suppliers.search': 'വിതരണക്കാരെയോ മെറ്റീരിയലുകളെയോ തിരയുക...',
    'suppliers.category': 'വിഭാഗം',
    'suppliers.city': 'നഗരം',
    'suppliers.allCategories': 'എല്ലാ വിഭാഗങ്ങളും',
    'suppliers.allCities': 'എല്ലാ നഗരങ്ങളും',
    'suppliers.listView': 'ലിസ്റ്റ് വ്യൂ',
    'suppliers.mapView': 'മാപ്പ് വ്യൂ',
    'suppliers.noResults': 'വിതരണക്കാരെ കണ്ടെത്തിയില്ല',
    'suppliers.noResults.desc': 'നിങ്ങളുടെ തിരയൽ മാനദണ്ഡങ്ങൾ ക്രമീകരിക്കുക അല്ലെങ്കിൽ എല്ലാ വിതരണക്കാരെയും ബ്രൗസ് ചെയ്യുക',
    'suppliers.contact': 'വിതരണക്കാരനെ ബന്ധപ്പെടുക',
    'suppliers.directions': 'ദിശകൾ നേടുക',
    'suppliers.totalSuppliers': 'മൊത്തം വിതരണക്കാർ',
    'suppliers.citiesCovered': 'ഉൾപ്പെടുത്തിയ നഗരങ്ങൾ',
    'suppliers.categories': 'വിഭാഗങ്ങൾ',
    'suppliers.avgRating': 'ശരാശരി റേറ്റിംഗ്',
  },
  mr: {
    // Navigation - keeping it short for brevity
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.yourIdea': 'तुमची कल्पना',
    'nav.businessPlan': 'व्यवसाय योजना',
    'nav.designStudio': 'डिझाइन स्टुडिओ',
    'nav.marketing': 'मार्केटिंग',
    'nav.suppliers': 'पुरवठादार',
    'nav.logout': 'लॉग आउट',
    'dashboard.hero.title': 'आजच कोणताही लहान व्यवसाय सुरू करा.',
    'dashboard.hero.description': 'भारतीय उद्योजकांसाठी डिझाइन केलेल्या AI-समर्थित साधनांसह तुमची व्यवसाय कल्पना लॉन्च-रेडी बिझनेस किटमध्ये रूपांतरित करा.',
    'dashboard.hero.cta': 'सुरू करा',
    'suppliers.title': 'पुरवठादार आणि स्थानिक डीलर',
    // ... other translations
  },
  or: {
    // Navigation - Odia
    'nav.dashboard': 'ଡ୍ୟାସବୋର୍ଡ',
    'nav.yourIdea': 'ଆପଣଙ୍କର ଧାରଣା',
    'nav.businessPlan': 'ବ୍ୟବସାୟ ଯୋଜନା',
    'nav.designStudio': 'ଡିଜାଇନ୍ ଷ୍ଟୁଡିଓ',
    'nav.marketing': 'ମାର୍କେଟିଂ',
    'nav.suppliers': 'ଯୋଗାଣକାରୀ',
    'nav.logout': 'ଲଗ୍ ଆଉଟ୍',
    'dashboard.hero.title': 'ଆଜି ଯେକୌଣସି ଛୋଟ ବ୍ୟବସାୟ ଆରମ୍ଭ କରନ୍ତୁ.',
    'dashboard.hero.description': 'ଭାରତୀୟ ଉଦ୍ୟୋଗୀମାନଙ୍କ ପାଇଁ ଡିଜାଇନ୍ ହୋଇଥିବା AI-ଚାଳିତ ଉପକରଣ ସହିତ ଆପଣଙ୍କର ବ୍ୟବସାୟ ଧାରଣାକୁ ଲଞ୍ଚ-ରେଡି ବିଜନେସ୍ କିଟରେ ପରିଣତ କରନ୍ତୁ.',
    'dashboard.hero.cta': 'ଆରମ୍ଭ କରନ୍ତୁ',
    'suppliers.title': 'ଯୋଗାଣକାରୀ ଏବଂ ସ୍ଥାନୀୟ ଡିଲର',
    // ... other translations
  },
  gu: {
    // Navigation - Gujarati
    'nav.dashboard': 'ડેશબોર્ડ',
    'nav.yourIdea': 'તમારો વિચાર',
    'nav.businessPlan': 'બિઝનેસ પ્લાન',
    'nav.designStudio': 'ડિઝાઇન સ્ટુડિયો',
    'nav.marketing': 'માર્કેટિંગ',
    'nav.suppliers': 'સપ્લાયર્સ',
    'nav.logout': 'લોગ આઉટ',
    'dashboard.hero.title': 'આજે જ કોઈપણ નાનો વ્યવસાય શરૂ કરો.',
    'dashboard.hero.description': 'ભારતીય ઉદ્યોગસાહસિકો માટે ડિઝાઇન કરવામાં આવેલ AI-સંચાલિત સાધનો સાથે તમારા વ્યવસાયિક વિચારને લોન્ચ-રેડી બિઝનેસ કિટમાં રૂપાંતરિત કરો.',
    'dashboard.hero.cta': 'શરૂ કરો',
    'suppliers.title': 'સપ્લાયર્સ અને સ્થાનિક ડીલર્સ',
    // ... other translations
  },
  pa: {
    // Navigation - Punjabi
    'nav.dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'nav.yourIdea': 'ਤੁਹਾਡਾ ਵਿਚਾਰ',
    'nav.businessPlan': 'ਕਾਰੋਬਾਰੀ ਯੋਜਨਾ',
    'nav.designStudio': 'ਡਿਜ਼ਾਈਨ ਸਟੂਡੀਓ',
    'nav.marketing': 'ਮਾਰਕੀਟਿੰਗ',
    'nav.suppliers': 'ਸਪਲਾਇਰ',
    'nav.logout': 'ਲੌਗ ਆਊਟ',
    'dashboard.hero.title': 'ਅੱਜ ਹੀ ਕੋਈ ਵੀ ਛੋਟਾ ਕਾਰੋਬਾਰ ਸ਼ੁਰੂ ਕਰੋ.',
    'dashboard.hero.description': 'ਭਾਰਤੀ ਉੱਦਮੀਆਂ ਲਈ ਤਿਆਰ ਕੀਤੇ AI-ਸੰਚਾਲਿਤ ਟੂਲਸ ਨਾਲ ਆਪਣੇ ਕਾਰੋਬਾਰੀ ਵਿਚਾਰ ਨੂੰ ਲਾਂਚ-ਰੈਡੀ ਬਿਜ਼ਨਸ ਕਿੱਟ ਵਿੱਚ ਬਦਲੋ.',
    'dashboard.hero.cta': 'ਸ਼ੁਰੂ ਕਰੋ',
    'suppliers.title': 'ਸਪਲਾਇਰ ਅਤੇ ਸਥਾਨਕ ਡੀਲਰ',
    // ... other translations
  },
  bh: {
    // Navigation - Bhojpuri
    'nav.dashboard': 'डैशबोर्ड',
    'nav.yourIdea': 'राउर विचार',
    'nav.businessPlan': 'व्यापार योजना',
    'nav.designStudio': 'डिजाइन स्टूडियो',
    'nav.marketing': 'मार्केटिंग',
    'nav.suppliers': 'आपूर्तिकर्ता',
    'nav.logout': 'लॉग आउट',
    'dashboard.hero.title': 'आज हऽ कवनो छोट व्यापार शुरू करीं.',
    'dashboard.hero.description': 'भारतीय उद्यमी लोग खातिर डिजाइन कइल AI-संचालित उपकरण से आपन व्यापार विचार के लॉन्च-तैयार बिजनेस किट में बदलीं.',
    'dashboard.hero.cta': 'शुरू करीं',
    'suppliers.title': 'आपूर्तिकर्ता आ स्थानीय डीलर',
    // ... other translations
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
